apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
spec:
  generators:
    - git:
        repoURL: https://github.com/mercurial963/argocd-applicationset-demo.git
        revision: main
        files:
          - path: "tenants-discovery/**/config.json"
  template:
    metadata:
      name: '{{tenant.id}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mercurial963/argocd-applicationset-demo.git
        targetRevision: main
        path: 'tenants/{{tenant.id}}'
        helm:
          valueFiles:
            - values.{{tenant.id}}.yaml
      destination:
        server: '{{k8s_cluster.address}}'
        namespace: '{{k8s_cluster.namespace}}'
      syncPolicy:
        automated: 
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true
      ignoreDifferences:
      # - group: *
      # - kind: "Deployment"
      #   jsonPointers:
      #   - /spec/replicas